pid: "./pid" #记录进程pid的文件路径
snap_path: "./" #存放报告日志的文件路径
alter_limit: 80.0 #告警线
interval: 10 #cpu负载采集间隔， 单位秒

fromMail: "873085747@qq.com" #发送人邮箱地址
fromMailHost: "smtp.qq.com" #邮箱服务器地址
fromMailPass: "****" #邮箱授权码
fromMailPort: "25" #邮箱服务器端口
toMail:
  - "873085747@qq.com"